def htmlEmailSucesso(descBot, tempExec, dataHoraExec, idExec, cnpj, codEmpresa):
    html = '<body style="margin: 0; margin: 0; box-sizing: border-box;">'
    html += '<table width="100%" align="center" cellpadding="0" cellspacing="0" style="max-width: 750px; margin: 0 auto;">'
    html += '<tr>'
    html += '<td style="padding: 20px 0 20px 0;background-color: #ccc;" bgcolor="#ccc" align="center">'
    html += '<img src = "https://www.tscti.com.br/wp-content/uploads/2019/03/Logo-TSCTI-300x104.png" alt = "" >'
    html += '</td>'
    html += '</tr>'
    html += '<tr>'
    html += '<td style="padding: 20px;" bgcolor="#fff">'
    html += f'<p style="font-size: 1.5em; font-weight: bold;">Olá, informamos que o seu {descBot} foi executado com <span style="color: green;">sucesso</span>! <br /> Segue algumas informações sobre a execução:</p>'
    html += '</td>'
    html += '</tr>'
    html += '<tr>'
    html += '<td style="padding: 20px;">'
    html += '<table width="100%" align="center" cellpadding="0" cellspacing="0" bgcolor="white" style="max-width: 750px;  margin: 0 auto;">'
    html += '<tr>'
    html += '<td>Tempo de execução:</td>'
    html += f'<td align="right" style="padding-bottom: 15px; ">{tempExec}</td>'
    html += '</tr>'
    html += '<tr>'
    html += '<td>Data e Hora:</td>'
    html += f'<td align="right" style="padding-bottom: 15px; ">{dataHoraExec}</td>'
    html += '</tr>'
    html += '<tr>'
    html += '<td>Código da execução:</td>'
    html += f'<td align="right" style="padding-bottom: 20px; ">{idExec}</td>'
    html += '</tr>'
    html += '<tr>'
    html += '<td>CNPJ:</td>'
    html += f'<td align="right" style="padding-bottom: 20px; ">{cnpj}</td>'
    html += '</tr>'
    html += '<tr>'
    html += '<td>Código da empresa:</td>'
    html += f'<td align="right" style="padding-bottom: 20px; ">{codEmpresa}</td>'
    html += '</tr>'
    html += '<tr>'
    html += '<td colspan="2">'
    html += '<h2 style="text-align: center;">Segue arquivo em anexo!</h2>'
    html += '</td>'
    html += '</tr>'
    html += '</table>'
    html += '</td>'
    html += '</tr>'
    html += '<tr>'
    html += '<table width = "100%" align = "center" bgcolor = "#ccc" cellpadding = "0" cellspacing = "0" style = "max-width: 750px;  margin: 0 auto;background-color: #ccc;" >'
    html += '<tr>'
    html += '<td  style="padding: 20px;">'
    html += '<img src="https://www.tscti.com.br/wp-content/uploads/2019/03/Logo-TSCTI-300x104.png" alt="">'
    html += '</td>'
    html += '<td>'
    html += '<h2 style="text-align: center; color: black; font-size: 1.2em; font-weight: bold;">Tecnologia | RPA | IA</h2>'
    html += '<p>(11) 3729-7237 | 9.9735-2852</p>'
    html += '<p>Rua Geraldo Campos Moreira, 164, 1º andar <br /> 04571-020 - São Paulo - SP</p>'
    html += '<p><a href="http://www.tscti.com.br/" target="_blank">www.tscti.com.br</a></p>'
    html += '</td>'
    html += '</tr>'
    html += '<tr>'
    html += '<td  style="padding: 0 0 20px 0;" align="center" colspan="2">'
    html += '<a href="https://cloudmarketplace.oracle.com/marketplace/pt_BR/listing/72612373" target="_blank">'
    html += '<img width="150px" src="https://www.tscti.com.br/wp-content/uploads/2018/01/Oracle-logo.png" alt="">'
    html += '</a>'
    html += '</td>'
    html += '</tr>'
    html += '</table>'
    html += '</tr>'
    html += '</table>'
    html += '</body>'

    return html